import pytest
from src.schemas.data_models import Requirement, CandidatePair, NumericalValue
from src.agents.reasoning import LogicalReasoningAgent
from src.agents.representation import KnowledgeRepresentationAgent

def test_permission_rule_representation():
    req1 = Requirement(requirement_id="REQ-001", original_text="Students shall be allowed to register for events.", actor="Students", action="register", object="events", source_page=1)
    req2 = Requirement(requirement_id="REQ-002", original_text="Only administrators shall be allowed to register students.", actor="administrators", action="register", object="students", source_page=1)
    
    agent = LogicalReasoningAgent()
    result = agent.evaluate_pair(req1, req2)
    
    # Actions overlap, but actors are different.
    assert result.has_overlapping_actions is True
    assert result.has_different_actors is True
    assert "Different actors" in result.reasoning_details

def test_numerical_constraint_comparison():
    req1 = Requirement(requirement_id="REQ-003", original_text="respond in 300 ms", action="respond", numerical_values=[NumericalValue(value=300, unit="ms")], source_page=1)
    req2 = Requirement(requirement_id="REQ-004", original_text="respond in 500 ms", action="respond", numerical_values=[NumericalValue(value=500, unit="ms")], source_page=1)
    
    agent = LogicalReasoningAgent()
    result = agent.evaluate_pair(req1, req2)
    
    assert result.has_numerical_overlap is True
    assert "300.0 vs 500.0" in result.numerical_comparison

def test_condition_representation():
    req1 = Requirement(requirement_id="REQ-005", original_text="Log it if fail", action="log", conditions=["if fail"], source_page=1)
    req2 = Requirement(requirement_id="REQ-006", original_text="Log it", action="log", source_page=1)
    
    agent = LogicalReasoningAgent()
    result = agent.evaluate_pair(req1, req2)
    
    assert result.has_conditional_implication is True

def test_evaluate_candidates_batch():
    req1 = Requirement(requirement_id="R1", original_text="test 1", action="test", actor="a", source_page=1)
    req2 = Requirement(requirement_id="R2", original_text="test 2", action="test", actor="b", source_page=1)
    
    candidate_pair = CandidatePair(requirement_id_1="R1", requirement_id_2="R2", similarity_score=0.9, requirement_text_1="test 1", requirement_text_2="test 2")
    
    agent = LogicalReasoningAgent()
    results = agent.evaluate_candidates([req1, req2], [candidate_pair])
    
    assert len(results) == 1
    assert results[0].has_different_actors is True

def test_integration_knowledge_and_reasoning():
    # 1. Version 2 objects
    req1 = Requirement(
        requirement_id="SYS-01",
        original_text="The system shall wait 10 seconds.",
        actor="The system",
        action="wait",
        numerical_values=[NumericalValue(value=10, unit="seconds")],
        source_page=1
    )
    req2 = Requirement(
        requirement_id="SYS-02",
        original_text="The system shall wait 20 seconds.",
        actor="The system",
        action="wait",
        numerical_values=[NumericalValue(value=20, unit="seconds")],
        source_page=1
    )
    
    # 2. Knowledge Representation
    kg_agent = KnowledgeRepresentationAgent()
    representations = kg_agent.transform([req1, req2])
    
    assert len(representations) == 2
    assert any(e.label == "NumericalValue" and e.name == "10.0 seconds" for e in representations[0].entities)
    
    # 3. Logical Reasoning
    # Note: We simulate Candidate Pair being generated by V3
    pair = CandidatePair(requirement_id_1="SYS-01", requirement_id_2="SYS-02", similarity_score=0.95, requirement_text_1="", requirement_text_2="")
    
    reasoning_agent = LogicalReasoningAgent()
    results = reasoning_agent.evaluate_candidates([req1, req2], [pair])
    
    assert len(results) == 1
    reasoning = results[0]
    
    assert reasoning.has_overlapping_actions is True
    assert reasoning.has_different_actors is False
    assert reasoning.has_numerical_overlap is True
    assert "10.0 vs 20.0" in reasoning.numerical_comparison
